# Generated by Django 3.2.15 on 2022-11-08 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('status', models.IntegerField(default=0, choices=((0, 'Draft'), (1, 'Published')), blank=True)),
            ],
        ),
    ]
